name: Actualizacion de Repositorios
on:
  push:
    branches: 
       [main]
jobs:
  Actualizacion_Repositorios:
     runs-on: windows-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Actualizar
         run: git fetch
       - name: enviar cambios
         run: git push
